import QuickStabilize from "../../public/assets/images/quick-easy-stabilize.png";
import CleanPowerLines from "../../public/assets/images/clean-power-lines.png";
import ReduceHarmfulElectricity from "../../public/assets/images/reduce-harmful-electricity.png";
import PowerCompensation from "../../public/assets/images/power-compensation.png";
import BufferElectricCurrent from "../../public/assets/images/buffer-electric-current.png";
import EasyToInstall from "../../public/assets/images/easy-to-install.png";
import SafeReliable from "../../public/assets/images/safe-reliable.png";
import ProtectAppliances from "../../public/assets/images/protect-appliances.png";
import StabilizesThePower from "../../public/assets/images/stabilizes-the-power.png";
import EliminatesShocks from "../../public/assets/images/eliminates-shocks.png";
import ReducesDirtyEmf from "../../public/assets/images/reduces-dirty-emf.png";
import StopwattGifStep1 from "../../public/assets/images/stopwatt-gif-step-1.gif";
import StopwattGifStep2 from "../../public/assets/images/stopwatt-gif-step-2.jpeg";
import StopwattGifStep3 from "../../public/assets/images/stopwatt-gif-step-3.jpeg";
import MoneyBack from "../../public/assets/images/money-back.png";
import Returns from "../../public/assets/images/returns.png";
import Delivery from "../../public/assets/images/delivery.png";
import FromUsa from "../../public/assets/images/from-usa.png";
import StopwattOne from "../../public/assets/images/mw-product-1.png";
import StopwattThree from "../../public/assets/images/mw-product-3.png";
import StopwattTwo from "../../public/assets/images/mw-product-2.png";

export const STOPWATT_BENEFITS = [
  {
    text: "Quickly and Easily Stabilize Your Homes Electrical Current",
    imageUrl: QuickStabilize,
    isActive: true,
    isInverse: true
  },
  {
    text: "Clean Power Lines and Reduce Electric Temperature",
    imageUrl: CleanPowerLines,
    isActive: false,
    isInverse: true
  },
  {
    text: "Reduce Harmful Dirty Electricity From Your Home",
    imageUrl: ReduceHarmfulElectricity,
    isActive: false,
    isInverse: true
  },
  {
    text: "On-The-Spot Reactive Power Compensation",
    imageUrl: PowerCompensation,
    isActive: false,
    isInverse: true
  },
  {
    text: "Absorption of Harmonic Waves + Buffer Electric Current Shock",
    imageUrl: BufferElectricCurrent,
    isActive: false,
    isInverse: false
  },
  {
    text: "Easy to Install, No Maintenance Required",
    imageUrl: EasyToInstall,
    isActive: false,
    isInverse: false
  },
  {
    text: "Safe, Reliable and Works in Any Home",
    imageUrl: SafeReliable,
    isActive: false,
    isInverse: false
  },
  {
    text: "Protect and Prolong the Life of Your Appliances & Electronics",
    imageUrl: ProtectAppliances,
    isActive: false,
    isInverse: false
  }
];

export const STOPWATT_USAGE = [
  {
    title: "Stabilizes the Power",
    description:
      "With groundbreaking Electricity Stabilizing Technology (E.S.T.), StopWatt is able to straighten the unstable electric current and provide a constant, smooth output. This improves the flow of power throughout the home and leads to a more efficient system.",
    imageUrl: StabilizesThePower
  },
  {
    title: "Eliminates Harmful Shocks & Surges",
    description:
      "Using advanced capacitors, StopWatt is able to eliminate the harmful spikes of electricity and prevent damage to appliances and electronics.",
    imageUrl: EliminatesShocks
  },
  {
    title: "Reduces Dirty EMF Electricity",
    description:
      "The patent-pending magnetic filter removes carbon from the electrical circuit helping to significantly reduce your exposure to harmful electromagnetic radiation (EMF/EMR) generated by your electronics, appliances, and dirty electrical system.",
    imageUrl: ReducesDirtyEmf
  }
];

export const STOPWATT_STEPS = [
  {
    title: "PLUG-IN YOUR DEVICE",
    description:
      "For one device, find a location as close as possible to your breaker box. For multiple devices, install each unit on a separate breaker. Separate floors or opposite ends of the home will work best.",
    imageUrl: StopwattGifStep1
  },
  {
    title: "MAKE SURE YOUR DEVICE IS WORKING",
    description:
      "The green light will illuminate when the device is plugged into an active outlet and begins to filter and stabilize the electrical current.",
    imageUrl: StopwattGifStep2
  },
  {
    title: "FILTER, STABILIZE AND SAVE",
    description:
      "The average home takes 2-3 weeks to stabilize the current and filter the EMF dirty electricity. Therefore, please allow up to 6-8 weeks to start seeing the benefits and results.",
    imageUrl: StopwattGifStep3
  }
];

export const PRODUCT_FEATURES = [
  {
    text: "Days Money Back Guarantee",
    imageUrl: MoneyBack
  },
  {
    text: "No-Hassle Returns",
    imageUrl: Returns
  },
  {
    text: "Quick Delivery",
    imageUrl: Delivery
  },
  {
    text: "From USA",
    imageUrl: FromUsa
  }
];

export const STOPWATT_PRICINGS = {
  153: {
    productName: "ONE StopWatt",
    description: "Small House 800-1200 sq.ft",
    imageUrl: StopwattOne,
    warrantyProductId: 156
  },
  155: {
    productName: "Three StopWatt(S)",
    description: "Large House 1500+ sq.ft",
    imageUrl: StopwattThree,
    warrantyProductId: 158,
    isPopular: true
  },
  154: {
    productName: "TWO StopWatt(S)",
    description: "Medium House 1200-1500 sq.ft",
    imageUrl: StopwattTwo,
    warrantyProductId: 157
  }
};

export const ESAVER_PRICINGS = {
  134: {
    productName: "ONE ESaver",
    description: "Small House 800-1200 sq.ft",
    imageUrl: StopwattOne,
    warrantyProductId: 137
  },
  136: {
    productName: "Three ESaver(S)",
    description: "Large House 1500+ sq.ft",
    imageUrl: StopwattThree,
    warrantyProductId: 139,
    isPopular: true
  },
  135: {
    productName: "TWO ESaver(S)",
    description: "Medium House 1200-1500 sq.ft",
    imageUrl: StopwattTwo,
    warrantyProductId: 138
  }
};

export const SETUP = [
  {
    id: "6",
    productName: "StopWatt",
    productTags: ["energy-saving"],
    description: `
          <div className="ProductDescriptionExcerpt">
              <p>StopWatt represents cutting-edge technology designed to reduce electricity expenses and minimize environmental impact. Easily connectable to standard electrical sockets, this device utilizes advanced technology to monitor and optimize energy usage in your household.</p>            
              <p>Through the analysis and adjustment of electric current, StopWatt significantly reduces the energy consumed by your home appliances and devices without compromising their effectiveness or operation. By incorporating StopWatt, you can achieve substantial cost savings on your electricity bills, with the potential for savings of up to 30%. This represents a wise investment that contributes to both your financial well-being and the planet's health.</p>        
              <p>Choose StopWatt now and take a crucial step towards reducing your carbon footprint while enjoying notable savings on your electricity bills.</p>
          </div>`,
    productImages: [
      "/assets/images/stopwatt-1.jpg",
      "/assets/images/stopwatt-2.jpg",
      "/assets/images/stopwatt-3.jpg"
    ]
  },
  {
    id: "7",
    productName: "Esaver Watt",
    productTags: ["energy-saving"],
    description: `
          <div className="ProductDescriptionExcerpt">
              <p>Esaver Watt stands as a groundbreaking energy-saving device crafted to cut down on your electricity expenses and diminish your carbon footprint. This gadget easily connects to any standard electrical outlet, actively overseeing and reducing the electricity consumption in your home.</p>
              <p>Employing advanced technology, Esaver Watt analyzes the electricity flow and optimizes it for efficiency without compromising the performance of your appliances or electronics.</p>  
              <p>By integrating Esaver Watt into your home, you can anticipate saving up to 30% on your energy bill, making it a commendable investment for both your financial well-being and the environment. Begin your savings journey today with Esaver Watt!</p>
          </div>`,
    productImages: [
      "/assets/images/esaver-watt-1.jpg",
      "/assets/images/esaver-watt-2.jpg",
      "/assets/images/esaver-watt-3.jpg"
    ]
  },
  {
    id: "3",
    productName: "Laundry Balls",
    productTags: ["laundry"],
    description: `
          <div className="ProductDescriptionExcerpt">
              <p>A sustainable and innovative alternative to traditional laundry detergents comes in the form of laundry balls. These reusable balls emit ions that penetrate fabric, efficiently removing dirt and stains without the use of harmful chemicals. This results in clothes that are fresh and clean-smelling, all without the inconvenience of measuring and pouring detergent on laundry day. Additionally, the balls' reusability leads to long-term cost savings and a decrease in waste. To use them, simply toss the balls into the wash with your clothes and experience the advantages of a cleaner and environmentally friendly laundry cycle.</p>
          </div>`,
    productImages: [
      "/assets/images/laundry-balls-1.jpg",
      "/assets/images/laundry-balls-2.jpg",
      "/assets/images/laundry-balls-3.jpg"
    ]
  },
  {
    id: "4",
    productName: "Dryer Balls",
    productTags: ["laundry"],
    description: `
          <div className="ProductDescriptionExcerpt">
              <p>Dryer balls offer a straightforward and economical method for softening your clothes, minimizing static, and expediting drying time—all while conserving energy. Crafted from wool or plastic, these balls move around in the dryer, creating separation among clothes and facilitating more efficient circulation of hot air. Beyond the cost savings on energy bills, they serve as an environmentally friendly option to dryer sheets, being reusable and devoid of chemicals. Just toss them into the dryer with your laundry load, and relish softer, fluffier clothes with reduced static cling.
              </p>
          </div>`,
    productImages: [
      "/assets/images/dryer-balls-1.jpg",
      "/assets/images/dryer-balls-2.jpg",
      "/assets/images/dryer-balls-3.jpg"
    ]
  },
  {
    id: "5",
    productName: "Washing Machine Tablet",
    productTags: ["laundry"],
    description: `
          <div className="ProductDescriptionExcerpt">
              <p>Bid farewell to unpleasant smells and a grimy washing machine with our potent cleaner tablets. Specially crafted to combat mold, bacteria, and residues that contribute to foul odors, these tablets are designed to clean and maintain the internal components of your machine. Utilizing our cleaner tablets is a breeze—simply drop one into your machine, run a cycle, and revel in a washing machine that's fresh and free from odors. Compatible with all types of washing machines and crafted with environmentally friendly ingredients, you can confidently use these tablets in your home. Regular use will not only prevent future buildup but also ensure your machine functions smoothly for years to come.</p>
          </div>`,
    productImages: [
      "/assets/images/washing-machine-tablet-1.jpg",
      "/assets/images/washing-machine-tablet-2.jpg",
      "/assets/images/washing-machine-tablet-3.jpg"
    ]
  },
  {
    id: "12",
    productName: "Solar Powerbank",
    productTags: ["gadgets"],
    description: `
          <div className="ProductDescriptionExcerpt">
              <p>A portable battery pack boasting an impressive 20000mAh capacity, indicating its ability to store substantial power and recharge devices multiple times. The robust and durable construction implies longevity and resilience against wear and tear, making it particularly valuable for outdoor enthusiasts who depend on durable and reliable equipment.</p>
              <h4>What is a Solar Power Bank?</h4>
              <br/>
              <p>The presence of five light indicators serves as a visual means to monitor the remaining battery life, aiding in strategic planning for recharging the pack as needed.</p>
              <p>The inclusion of a built-in carabiner adds a practical touch, facilitating easy attachment of the battery pack to a backpack or belt loop. This proves convenient for individuals on the move who require a continuous charge for their devices.</p>
              <p>
              Additionally, the reference to solar charging implies the presence of a solar panel capable of converting sunlight into power. However, the effectiveness of this feature depends on sunlight intensity and panel quality. Solar charging is likely intended as an auxiliary function, and charging times may fluctuate based on environmental conditions.</p>
          </div>`,
    productImages: [
      "/assets/images/solar-powerbank-1.jpg",
      "/assets/images/solar-powerbank-2.jpg",
      "/assets/images/solar-powerbank-3.jpg"
    ]
  },
  {
    id: "14",
    productName: "CamHandy",
    productTags: ["gadgets"],
    description: `
          <div className="ProductDescriptionExcerpt">      
                  <p>
                      <b>Capture Every Moment on the Road with Confidence! </b> <br><br>
                      Never miss a moment on the road again with our advanced dashcam! Here's why it's a must-have addition to your vehicle
                  </p>
                  <h4><b>  Product Features:</b> </h4>
                  <ul style="display:inline-block">
                      <li style="display:inline-block;"><b>Full 1080p HD | </b></li>
                      <li style="display:inline-block"><b>Night Vision | </b></li>
                      <li style="display:inline-block"><b>Automatic Recording</b></li>
                  </ul>
                  <hr>                
                  <ul>
                      <li><p><b>Crystal-Clear Footage </b> Our dashcam records in stunning [1080p/1440p/4K] resolution, ensuring that every detail is captured crisply and clearly. From license plates to road signs, you'll have a precise record of your journey.</p></li>
                      <li><p><b>Wide-Angle Vision </b> With a [120/140/170]-degree wide-angle lens, our dashcam covers more than just the road ahead. It captures multiple lanes and the surroundings, ensuring a comprehensive view of your entire drive.</p></li>
                      <li><p><b>Peace of Mind with Loop Recording </b> Say goodbye to the worry of running out of storage space! Our dashcam features loop recording, automatically overwriting older footage to ensure continuous recording without any hassle.</p></li>
                      <li><p><b>Emergency Recording with G-Sensor </b> In the event of sudden stops or collisions, our dashcam's G-Sensor kicks in, locking and preserving the footage to ensure crucial evidence is retained for insurance claims or legal purposes.</p></li>
                      <li><p><b>Protection Around the Clock </b> Activate the parking mode and let our dashcam continue to monitor your vehicle even when parked. Motion detection or impact sensors ensure surveillance and protection, safeguarding your car from potential accidents or vandalism.</p></li>
                      <li><p><b>Seamless Connectivity </b> Easily access your footage on the go! Our dashcam comes equipped with Wi-Fi connectivity, allowing you to view, download, or share videos directly from your smartphone via our user-friendly app.</p></li>
                      <li><p><b>Enhanced Visibility at Night </b> With superior low-light capabilities or infrared sensors, our dashcam ensures clear and detailed footage even in dark or low-light conditions, providing unmatched visibility at any hour.</p></li>
                      <li><p><b>GPS Tracking for Added Context </b> Log your vehicle's location and speed with built-in GPS, providing comprehensive context for your recorded footage, making it invaluable for insurance claims or route tracking.</p></li>
                      <li><p><b>Easy Installation and User-Friendly Interface </b> Installing and operating our dashcam is a breeze! With its intuitive interface and easy setup, you'll be up and running in no time.</p></li>
                  </ul>
                  <p>Don't just drive; capture your journey with confidence and security. Invest in our dashcam today and enjoy peace of mind on every ride!</p>
          </div>`,
    productImages: [
      "/assets/images/camhandy-1.jpg",
      "/assets/images/camhandy-2.jpg",
      "/assets/images/camhandy-3.jpg"
    ]
  },
  {
    id: "16",
    productName: "Fuel Saver",
    productTags: ["energy-saving"],
    description: `
          <div className="ProductDescriptionExcerpt">       
              <p>
                  Prepare to redefine your driving experience with Fuel Saver  – the innovation you didn't know you needed, until now.
              </p>
              <br>
              <p><b>*Why Fuel Saver  Stands Out:*</b></p>
              <ul>
                  <li><b>Discover the Fuel Saver  Difference:</b><p> Your Passport to Enhanced Fuel Efficiency</p> </li>
                  <li><b>Optimize Fuel Use:</b><p> With Fuel Saver , tap into the potential of your vehicle to maximize every drop of gasoline.</p></li>
                  <li><b>Plug &amp; Play Simplicity:</b><p> Forget complex setups. Fuel Saver  is the epitome of convenience, designed for immediate impact.</p></li>
                  <li><b>Universal Compatibility:</b><p> No matter your ride, Fuel Saver  brings its magic to a wide array of vehicles.</p></li>
              </ul>
              <p>
                With Fuel Saver , you're not just buying a product; you're investing in a lifestyle. A lifestyle where efficiency meets economy. Why settle for less when you can drive smarter, cleaner, and cheaper?
              </p>
          </div>`,
    productImages: [
      "/assets/images/fuel-saver-1.jpg",
      "/assets/images/fuel-saver-2.jpg",
      "/assets/images/fuel-saver-3.jpg"
    ]
  },
  {
    id: "20",
    productName: "Ultra Air Heater",
    productTags: ["gadgets"],
    description: `
          <div className="ProductDescriptionExcerpt">       
              <p>
                  Prepare to redefine your driving experience with Fuel Saver  – the innovation you didn't know you needed, until now.
              </p>
              <br>
              <p><b>*Why Fuel Saver  Stands Out:*</b></p>
              <ul>
                  <li><b>Discover the Fuel Saver  Difference:</b><p> Your Passport to Enhanced Fuel Efficiency</p> </li>
                  <li><b>Optimize Fuel Use:</b><p> With Fuel Saver , tap into the potential of your vehicle to maximize every drop of gasoline.</p></li>
                  <li><b>Plug &amp; Play Simplicity:</b><p> Forget complex setups. Fuel Saver  is the epitome of convenience, designed for immediate impact.</p></li>
                  <li><b>Universal Compatibility:</b><p> No matter your ride, Fuel Saver  brings its magic to a wide array of vehicles.</p></li>
              </ul>
              <p>
                With Fuel Saver , you're not just buying a product; you're investing in a lifestyle. A lifestyle where efficiency meets economy. Why settle for less when you can drive smarter, cleaner, and cheaper?
              </p>
          </div>`,
    productImages: [
      "/assets/images/ultra-air-heater-1.jpg",
      "/assets/images/ultra-air-heater-2.jpg",
      "/assets/images/ultra-air-heater-3.jpg"
    ]
  }
];

export const SW_COUPON_DISCOUNT = 50;
